class EnvironmentSettings:
    def __init__(self):
        self.workspace_dir = '/home/professor12/OSTrack-main/output'
        self.tensorboard_dir = self.workspace_dir + '/tensorboard/'
        self.pretrained_networks = '/home/professor12/OSTrack-main/pretrained_models'

        data_dir = '/home/professor12/OSTrack-main/data'
        self.lasot_dir = data_dir + '/lasot/train'
        self.lasot_lmdb_dir = data_dir + '/lasot_lmdb'
        self.got10k_dir = data_dir + '/got10k/train'
        self.got10k_val_dir = data_dir + '/got10k/val'
        self.got10k_lmdb_dir = data_dir + '/got10k_lmdb'
        self.trackingnet_dir = data_dir + '/trackingnet'
        self.trackingnet_lmdb_dir = data_dir + '/trackingnet_lmdb'
        self.coco_dir = data_dir + '/coco'
        self.coco_lmdb_dir = data_dir + '/coco_lmdb'
        self.lvis_dir = ''
        self.sbd_dir = ''
        self.imagenet_dir = data_dir + '/vid'
        self.imagenet_lmdb_dir = data_dir + '/vid_lmdb'
        self.imagenetdet_dir = ''
        self.ecssd_dir = ''
        self.hkuis_dir = ''
        self.msra10k_dir = ''
        self.davis_dir = ''
        self.youtubevos_dir = ''
